set -g prefix ^A
set -g base-index 1
set -g renumber-windows on # renumber windows when one closed
set -g detach-on-destroy off # don't exit when a session destroyed
set -g history-limit 1000000
set -g set-clipboard on
set -g status-position top
setw -g mode-keys vi
set -g status-interval 3

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
run-shell ~/.config/tmux/themes/ayu-dark-transparent.tmux

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run ~/.config/tmux/plugins/tpm/tpm

