##### status bar #####
set -g status on
set -g status-position bottom
set -g status-justify centre

set -g status-style "bg=default,fg=#b3b1ad"

set -g status-left-length 100
set -g status-right-length 100

##### left: current session + other sessions #####
set -g status-left "#[fg=#1f2430,bg=#ffb454,bold] #S #[fg=#bfbdb6,bg=default]#(~/.config/tmux/scripts/tmux-other-sessions.sh) "

##### right: battery + date + time #####
set -g status-right "#(~/.config/tmux/scripts/tmux-battery.sh) #[fg=#707a8c]│ #[fg=#ffd173] %B %d, %Y #[fg=#707a8c]│ #[fg=#59c2ff] %H:%M "

##### middle: native tmux window list #####
set -g window-status-separator ""

set -g window-status-format "#[fg=#b3b1ad,bg=default] #I:#W "
set -g window-status-current-format "#[fg=#1f2430,bg=#59c2ff,bold] #I:#W "

##### borders / messages #####
set -g message-style "bg=default,fg=#ffd173"
set -g message-command-style "bg=default,fg=#ffb454"

set -g pane-border-style "fg=#3a4152"
set -g pane-active-border-style "fg=#59c2ff"

set -g mode-style "bg=#ffd173,fg=#1f2430,bold"
