set -g status on
set -g status-position bottom

set -g status-style "bg=default,fg=#b3b1ad"

# We render everything ourselves
set -g status-left-length 200
set -g status-right-length 0
set -g status-left "#(~/.config/tmux/scripts/tmux-statusline.sh)"
set -g status-right ""

# disable native window list, since we draw our own
set -g window-status-format ""
set -g window-status-current-format ""
set -g window-status-separator ""

set -g message-style "bg=default,fg=#ffd173"
set -g message-command-style "bg=default,fg=#ffb454"

set -g pane-border-style "fg=#3a4152"
set -g pane-active-border-style "fg=#59c2ff"

set -g mode-style "bg=#ffd173,fg=#1f2430,bold"
